name: dependabot-auto-merge

on:
  pull_request:

permissions: write-all

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: all
          github-token: ${{ secrets.DEPENDABOT_AUTO_MERGE }}
